"""Service for generating educational scripts using the Anthropic Claude API.

Each scene gets complete, runnable ManimCE Python code generated by the LLM.
This replaces the old template-based approach with direct LLM code generation
— matching the arxivisual architecture that produces 3Blue1Brown-quality
animations.
"""

import asyncio
import json
import logging
import re
import time
from typing import Optional

import anthropic

from shared.contracts.character_schema import CHARACTER_PERSONALITIES
from shared.contracts.enums import Character, Difficulty
from shared.contracts.pipeline_schema import GeneratedScript

from ..config import settings
from .context7_docs import get_manim_docs

logger = logging.getLogger(__name__)

CLAUDE_MODEL = "claude-sonnet-4-20250514"

DIFFICULTY_INSTRUCTIONS: dict[Difficulty, str] = {
    Difficulty.BEGINNER: (
        "Explain concepts at a beginner level. Use simple language, avoid jargon, "
        "and break down ideas into the most fundamental building blocks."
    ),
    Difficulty.INTERMEDIATE: (
        "Explain at an intermediate level. Use some technical terms "
        "but always briefly clarify them. Build on foundational knowledge."
    ),
    Difficulty.ADVANCED: (
        "Explain at an advanced level. Use proper technical terminology, "
        "explore nuances, edge cases, and deeper implications."
    ),
}

# Built-in ManimCE reference so the LLM always has a baseline even if
# Context7 is unavailable.
MANIMCE_REFERENCE = r"""
MANIM COMMUNITY EDITION (ManimCE) — QUICK API REFERENCE
========================================================
You write complete ManimCE Python code. Import: from manim import *

TEXT & MATH MOBJECTS:
  Text("hello", font_size=36)           — titles, labels, prose (Pango/Cairo)
  MathTex(r"x^2 + 1 = 0")              — LaTeX math expressions
  MathTex(r"\frac{d}{dx} x^2 = 2x")   — fractions, derivatives, integrals
  MathTex(r"\int_0^1 x\,dx = \frac{1}{2}") — integrals with limits
  Tex(r"Hello \textbf{world}")          — LaTeX text mode
  ALWAYS use raw strings r"..." for MathTex/Tex content.
  Use Text() for plain titles/labels, MathTex() for equations and formulas.
  MathTex() and Tex() accept color= and font_size= as constructor args:
    MathTex(r"x^2", color=BLUE, font_size=36)
    Tex(r"Hello", color=RED)

SHAPES & GEOMETRY:
  Axes(x_range=[a,b,s], y_range=[c,d,s], x_length=7, y_length=5)
  IMPORTANT: Use small ranges like [-3,3,1]. NEVER wider than [-5,5,1].
  You can use x_length and y_length to control Axes size.
  You can also use axis_config, tips, include_numbers for Axes customisation.
  NumberPlane(x_range, y_range)
  NumberLine(x_range)
  Dot(point), Line(start, end), Arrow(start, end)
  Circle(radius=1.0), Square(side_length=1.0), Rectangle(width, height)
  RoundedRectangle(corner_radius=0.15, width=4, height=2)
  VGroup(mob1, mob2, ...)               — group mobjects together
  SurroundingRectangle(mob, color=YELLOW, buff=0.15)
  Brace(mob, direction)
  DashedLine(start, end)
  Polygon(*points), RegularPolygon(n=6)
  Arc(angle), AnnularSector(inner_radius, outer_radius, angle)

POSITIONING:
  mob.to_edge(UP/DOWN/LEFT/RIGHT, buff=0.5)
  mob.to_corner(UL/UR/DL/DR, buff=0.5)
  mob.next_to(other, DOWN, buff=0.3)
  mob.move_to(point_or_mob)
  mob.shift(RIGHT * 2 + UP * 1)
  VGroup(...).arrange(DOWN, buff=0.4)
  VGroup(...).arrange_in_grid(n_rows, n_cols, buff=0.3)

DIRECTIONS: UP, DOWN, LEFT, RIGHT, UL, UR, DL, DR, ORIGIN

ANIMATIONS (ManimCE names):
  Write(mob), Create(mob), FadeIn(mob), FadeOut(mob)
  FadeIn(mob, shift=UP*0.3)            — directional fade in
  Transform(src, dst), ReplacementTransform(src, dst)
  TransformMatchingTex(old_tex, new_tex) — animate matching LaTeX parts
  TransformMatchingShapes(old, new)     — morph non-Tex shapes
  Indicate(mob, color=YELLOW, scale_factor=1.2)
  Circumscribe(mob, color=YELLOW)       — draw a circle around mobject
  GrowFromCenter(mob), GrowArrow(arrow)
  MoveAlongPath(dot, path)
  LaggedStart(*anims, lag_ratio=0.2)    — staggered reveals (MANDATORY for lists)
  AnimationGroup(*anims)
  Flash(point, color=YELLOW)
  Unwrite(mob)                          — reverse of Write
  Wiggle(mob)                           — wiggle effect
  ApplyWave(mob)                        — wave effect

  IMPORTANT: Use Create() NOT ShowCreation(). Use Unwrite() NOT Uncreate().

PLAY:
  self.play(Create(mob), run_time=2)
  self.play(mob.animate.shift(RIGHT*2), run_time=1.5)
  self.play(mob.animate.set_color(YELLOW))
  self.play(mob.animate.set_opacity(0.3))  — dim previous elements
  self.wait(2)

AXES METHODS (ManimCE):
  graph = axes.plot(lambda x: x**2, color=BLUE, x_range=[-3,3])
  label = MathTex(r"x^2", color=BLUE, font_size=28).next_to(axes.c2p(2, 4), RIGHT)
  dot = Dot(axes.c2p(x, y))             — coordinate to point
  axes.get_graph_label(graph, label=MathTex(r"f(x)"))
  axes.input_to_graph_point(x_val, graph) — get point on graph at x
  area = axes.get_area(graph, x_range=[0, 2], color=BLUE, opacity=0.3)
  axes.add_coordinates()                 — show numbers on axes
  labels = axes.get_axis_labels(x_label="x", y_label="f(x)")

COLORS:
  BLUE, BLUE_A/B/C/D/E, RED, RED_A-E, GREEN, GREEN_A-E,
  YELLOW, YELLOW_A-E, GOLD, GOLD_A-E, TEAL, TEAL_A-E,
  PURPLE, PURPLE_A-E, MAROON, MAROON_A-E, ORANGE, PINK,
  GREY, GREY_A-D, WHITE, BLACK, GREY_BROWN

SCENE CLASS:
  class MyScene(Scene):
      def construct(self):
          ...

=== STRICT TYPOGRAPHY & LEGIBILITY RULES ===
- No walls of text — use bullet points, keywords, or short phrases only
- Minimum font sizes: headers 40-48, body 28-36, absolute minimum 24
- Use weight=BOLD for titles: Text("Title", font_size=44, weight=BOLD)
- Max 4-5 visual elements on screen at once
- NEVER display paragraphs of text. Use progressive reveal instead.

=== GRID LAYOUT SYSTEM (MANDATORY) ===
Frame: 14.2 x 8 units.  Safe zone: x in [-6.0, 6.0], y in [-3.2, 3.2].

Named grid positions — use these for ALL placement:
  TITLE_POS    = UP * 3.2               — title bar (always here)
  SUBTITLE_POS = UP * 2.3               — section headers / subtitle
  MAIN_AREA    = DOWN * 0.3             — primary content below title
  LEFT_PANEL   = LEFT * 3.2             — split-screen left
  RIGHT_PANEL  = RIGHT * 3.2            — split-screen right
  TOP_LEFT     = UP * 2.0 + LEFT * 3.5  — upper-left quadrant
  TOP_RIGHT    = UP * 2.0 + RIGHT * 3.5 — upper-right quadrant
  BOT_LEFT     = DOWN * 2.0 + LEFT * 3.5— lower-left quadrant
  BOT_RIGHT    = DOWN * 2.0 + RIGHT * 3.5 — lower-right quadrant
  BOTTOM_POS   = DOWN * 2.8             — footer / annotation area

Layout patterns — pick ONE per scene:
  Full Center:    Title at UP*3.2, single content at DOWN*0.3
  Split Screen:   Title at UP*3.2, text at LEFT*3.2, visual at RIGHT*3.2
  Vertical Stack: Title at UP*3.2, VGroup.arrange(DOWN, buff=0.4).move_to(DOWN*0.3)
  Graph Layout:   Title at UP*3.2, axes.move_to(DOWN*0.3)

Size safety — apply AFTER building groups:
  - VGroup with 4+ items:  group.set_height(min(group.get_height(), 5.5))
  - Horizontal with 3+ items: group.set_width(min(group.get_width(), 12.0))
  - NEVER .shift() with magnitude > 3.5
  - NEVER place content below y = -3.0 or above y = 3.5

=== COGNITIVE LOAD & FOCUS ANIMATION ===
- Dim previous elements when new content appears:
    self.play(prev_group.animate.set_opacity(0.3))
- Restore when revisiting: self.play(prev_group.animate.set_opacity(1.0))
- Emphasis animations:
    Indicate(mob, color=YELLOW)        — "Notice this..."
    Circumscribe(mob, color=YELLOW)    — "This is critical..."
    SurroundingRectangle(mob, color)    — persistent highlight
    ApplyWave(mob)                      — "Something interesting..."
- ALWAYS use LaggedStart for revealing lists:
    self.play(LaggedStart(*[FadeIn(b, shift=UP*0.3) for b in bullets], lag_ratio=0.2))
  NEVER FadeIn an entire VGroup at once.

=== SCENE LIFECYCLE — CLEAR BEFORE BUILD (MANDATORY) ===
Every construct() follows: TITLE -> BUILD -> (optional TRANSITION) -> CLEANUP.

1. Each scene starts with a blank frame — never rely on previous scene state.
2. Title always first: title.move_to(UP * 3.2) then build content below.
3. When a scene has two logical ideas, FadeOut ALL non-title elements between them:
     self.play(*[FadeOut(m) for m in self.mobjects if m is not title], run_time=1)
4. To keep specific elements (like axes), dim them with .set_opacity(0.3),
   add new content, then restore with .set_opacity(1.0).
5. The LAST two lines of EVERY construct() MUST be:
     self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
     self.wait(1)
   This ensures a clean transition to the next scene.

=== SUBJECT-SPECIFIC VISUAL ARCHETYPES ===
History/Literature: Line+Dot timelines, large quotation Text for blockquotes
Science: radial VGroup concept diagrams (central circle + radiating connectors)
Math/Physics: equations with TransformMatchingTex, graphs, vector diagrams
CS/Programming: box-and-arrow diagrams, array cells, tree structures

=== VISUAL-FIRST RULE — NEVER PLAIN TEXT WALLS (CRITICAL) ===
You MUST convert textual information into VISUAL STRUCTURES whenever possible.
If content is a list → build a TREE, TABLE, or FLOWCHART, NOT stacked Text lines.
If content describes relationships → use ARROWS, CONNECTORS, and DIAGRAMS.
If content describes categories → use GROUPED BOXES with color-coded sections.
If content describes a process → use a FLOWCHART with numbered boxes and arrows.
If content describes a hierarchy → use a TREE with parent/child connections.
If content describes comparisons → use a SIDE-BY-SIDE TABLE with columns.

Building a TABLE (2+ columns of info):
    headers = VGroup(
        Text("Property", font_size=28, weight=BOLD, color=YELLOW),
        Text("Value", font_size=28, weight=BOLD, color=YELLOW),
    ).arrange(RIGHT, buff=3.0).move_to(UP * 1.5)
    row1 = VGroup(
        Text("Name", font_size=26, color=WHITE),
        Text("Hash Table", font_size=26, color=BLUE),
    ).arrange(RIGHT, buff=2.2).next_to(headers, DOWN, buff=0.5)

Building a TREE (hierarchy):
    root = VGroup(
        RoundedRectangle(width=3, height=0.8, corner_radius=0.1, color=BLUE),
        Text("Root", font_size=28).move_to(ORIGIN),
    )
    root[1].move_to(root[0].get_center())
    child_a = VGroup(RoundedRectangle(..., color=GREEN), Text("Child A",...))
    child_a[1].move_to(child_a[0].get_center())
    # Position children below root
    child_a.next_to(root, DOWN + LEFT, buff=0.8)
    arrow_a = Arrow(root.get_bottom(), child_a.get_top(), buff=0.1, color=WHITE)

Building a FLOWCHART (process):
    step1 = VGroup(RoundedRectangle(width=3, height=0.7, color=BLUE),
                    Text("Step 1", font_size=26))
    step1[1].move_to(step1[0].get_center())
    step2 = VGroup(RoundedRectangle(width=3, height=0.7, color=GREEN),
                    Text("Step 2", font_size=26))
    step2[1].move_to(step2[0].get_center())
    steps = VGroup(step1, step2).arrange(DOWN, buff=1.2).move_to(DOWN * 0.3)
    arrow = Arrow(step1.get_bottom(), step2.get_top(), buff=0.1, color=WHITE)

MANDATORY: At least 3 out of 5-7 scenes MUST use visual structures (trees, tables,
flowcharts, diagrams, graphs) instead of plain stacked text. Text-only scenes are
only acceptable for the title/intro scene and the summary/outro scene.

=== TEXT OVERLAP PREVENTION — ABSOLUTE ZERO-TOLERANCE (CRITICAL) ===
Text MUST NEVER overlap with other text, unless it is an intentional Transform
animation where one text morphs into another (TransformMatchingTex, ReplacementTransform).

STRICT RULES:
1. Before placing NEW content, ALWAYS FadeOut or reposition ALL existing content:
     self.play(*[FadeOut(m) for m in self.mobjects if m is not title], run_time=1)
   OR dim it:
     self.play(existing_content.animate.set_opacity(0.3), run_time=0.5)

2. NEVER have two separate Text/MathTex objects that occupy the same or nearby y-position
   without at least 0.5 units of vertical gap between them. Check buff values.

3. When using .arrange(DOWN, buff=X), use buff >= 0.4 for text items.

4. When using .next_to(other, DOWN, buff=X), use buff >= 0.3.

5. For Transforms: the NEW MathTex/Text MUST be .move_to(old_object) BEFORE the Transform.
   This ensures they swap in-place and never coexist visually.

6. NEVER use .shift() to "move text down a bit" — it creates overlaps when content grows.
   Use .next_to() or .arrange() which compute positions from actual bounding boxes.

7. MAXIMUM 4 text elements visible simultaneously. If you need more,
   FadeOut earlier ones first, or use a scrolling/phased reveal approach.

8. When adding annotations (labels, braces, arrows) next to existing content,
   use .next_to() with buff >= 0.3 to guarantee no collision.

=== COLOR THEME & BACKGROUND (MANDATORY) ===
Background is BLACK (Manim default). ALL text and visuals must be designed for
dark background with high contrast.

Color assignments (use consistently across ALL scenes):
  TITLES:       Text(..., color=WHITE, weight=BOLD) or GOLD for emphasis
  SUBTITLES:    Text(..., color=GREY_A) or BLUE_A for section headers
  BODY TEXT:    Text(..., color=WHITE) — never grey on black (too dim)
  PRIMARY:      BLUE or BLUE_C — main concepts, primary objects, first graph
  SECONDARY:    GREEN or GREEN_C — supporting concepts, second graph, comparisons
  HIGHLIGHT:    YELLOW — key takeaways, currently active element, emphasis
  RESULT:       GREEN_B — final answers, conclusions, verified results
  WARNING/IMPORTANT: RED or RED_B — critical notes, errors, edge cases
  NEUTRAL:      GREY_A — dimmed previous elements, background annotations
  BOX BORDERS:  WHITE or color-matched to content (BLUE box for BLUE content)
  ARROWS:       WHITE — neutral connectors; or color-matched for emphasis

Rules:
1. NEVER use dark colors (GREY_D, GREY_E, DARK_BROWN) for text — invisible on black.
2. Title MUST be WHITE or GOLD. Never BLUE/GREEN/RED for the main title.
3. When dimming elements, use .set_opacity(0.3), NOT a darker color.
4. Every diagram/chart must use at least 2-3 distinct colors to differentiate parts.
5. Color-coded legend is recommended for scenes with 3+ categories.

=== ADVANCED ANIMATION TECHNIQUES ===
- Use LaggedStart with lag_ratio=0.2 for ALL lists — ban FadeIn(entire_group)
- Use TransformMatchingTex for formula evolution (not ReplacementTransform)
- Rate function variety: rush_into, rush_from, there_and_back, smooth
  Example: self.play(FadeIn(mob), run_time=1.5, rate_func=rush_from)

=== IMPORTANT RULES ===
1. Import MUST be: from manim import *
2. Class names: Scene000, Scene001, Scene002, etc.
3. Use Create() NOT ShowCreation(). Use Unwrite() NOT Uncreate().
4. MathTex() accepts color= and font_size= as constructor args.
5. Text() DOES accept color= and font_size= as constructor args.
6. Use axes.plot() NOT axes.get_graph(). Use axes.c2p() for coordinates.
7. You CAN use x_length= and y_length= on Axes to control size.
8. Use MathTex() for all math expressions. Use Tex() for LaTeX text.
9. You CAN use axis_config, tips, include_numbers on Axes.
10. Dim old content with .animate.set_opacity(0.3) when new content appears.
11. NEVER font_size below 24. NEVER .scale() below 0.8 on text.
12. ALL .to_edge() calls MUST use buff=0.5 or greater.
13. Use LaggedStart with lag_ratio=0.2 for lists — never FadeIn entire VGroup.
14. Every self.play() MUST have run_time=1.5 to 3 seconds.
15. Add self.wait(2) after important reveals.
16. Use grid positions for ALL placement. Title at UP * 3.2, content at DOWN * 0.3.
    NEVER use .to_edge(UP, buff=0.5) for titles — use .move_to(UP * 3.2).
17. EVERY scene MUST end with:
      self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
      self.wait(1)
18. NEVER import anything besides manim and numpy. No manim_physics, etc.
19. Guard graph lambdas against division by zero:
      WRONG:  lambda x: 1/x
      RIGHT:  lambda x: 1/x if abs(x) > 0.01 else 0
20. NEVER place text at the right edge of the frame. All text must have x-position
    between -5.5 and 4.5 to leave margin. Use .set_width(min(mob.get_width(), 10.0))
    on any text that might be long.
"""


def _fetch_live_manim_docs(source_text: str) -> str:
    """Fetch live Manim docs from Context7 based on the source material."""
    topic = "manim Scene Text Axes NumberPlane Create FadeIn Write Transform animations plot VGroup MathTex physics chemistry circuit automata data structures"
    logger.info("[script_gen] Fetching live Manim docs from Context7 (topic: %s)", topic)
    try:
        docs = asyncio.run(get_manim_docs(topic=topic, max_tokens=5000))
        if docs:
            logger.info("[script_gen] Context7 returned %d chars of live Manim docs", len(docs))
            return docs
        logger.warning("[script_gen] Context7 returned empty docs")
    except Exception as exc:
        logger.warning("[script_gen] Context7 fetch failed: %s — using built-in reference", exc)
    return ""


class ScriptGenerator:
    """Generates structured educational scripts with complete Manim code per scene."""

    def __init__(self) -> None:
        self.client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    def generate(
        self,
        extracted_text: str,
        character: Character,
        difficulty: Difficulty,
        user_prompt: Optional[str] = None,
    ) -> GeneratedScript:
        logger.info("[script_gen] ┌─ Generating script")
        logger.info("[script_gen] │  Character: %s", character.value)
        logger.info("[script_gen] │  Difficulty: %s", difficulty.value)
        logger.info("[script_gen] │  Source text: %d chars", len(extracted_text))
        logger.info("[script_gen] │  Model: %s", CLAUDE_MODEL)

        personality = CHARACTER_PERSONALITIES[character]
        difficulty_instruction = DIFFICULTY_INSTRUCTIONS[difficulty]

        t0 = time.perf_counter()
        live_docs = _fetch_live_manim_docs(extracted_text)
        docs_elapsed = time.perf_counter() - t0
        logger.info("[script_gen] │  Context7 fetch: %.1fs, %d chars", docs_elapsed, len(live_docs))

        system_prompt = self._build_system_prompt(
            personality, difficulty_instruction, live_docs
        )
        user_message = self._build_user_message(extracted_text, user_prompt)

        logger.info("[script_gen] │  System prompt: %d chars", len(system_prompt))
        logger.info("[script_gen] │  User message: %d chars", len(user_message))

        response_text, api_elapsed = self._request_script(system_prompt, user_message)
        logger.info("[script_gen] │  Response: %d chars", len(response_text))
        logger.info("[script_gen] │  Response preview: %.500s...", response_text)

        script_data = self._parse_response(response_text)

        quality_errors = self._validate_script_quality(script_data, personality)
        if quality_errors:
            logger.warning("[script_gen] │  First draft quality issues: %s", quality_errors)
            feedback = (
                "Regenerate the full JSON and fix ALL issues:\n- "
                + "\n- ".join(quality_errors)
            )
            retry_user_message = f"{user_message}\n\n{feedback}"
            response_text, retry_elapsed = self._request_script(system_prompt, retry_user_message)
            api_elapsed += retry_elapsed
            script_data = self._parse_response(response_text)
            quality_errors = self._validate_script_quality(script_data, personality)
            if quality_errors:
                logger.warning(
                    "[script_gen] │  Quality issues remain after retry: %s. Continuing with best effort.",
                    quality_errors,
                )

        script_data["character"] = character.value
        script_data["difficulty"] = difficulty.value
        script_data["language"] = "en"

        script = GeneratedScript(**script_data)
        logger.info("[script_gen] │  Title: %s", script.title)
        logger.info("[script_gen] │  Total scenes: %d", script.total_scenes)
        for i, s in enumerate(script.scenes):
            has_code = bool(s.manim_code)
            code_len = len(s.manim_code) if s.manim_code else 0
            logger.info(
                "[script_gen] │  Scene %d: type=%s, duration=%.0fs, has_code=%s (%d chars)",
                i + 1, s.manim_scene_type, s.duration_hint_seconds, has_code, code_len,
            )
        logger.info("[script_gen] └─ Script generation complete (%.1fs total)", docs_elapsed + api_elapsed)
        return script

    def _request_script(self, system_prompt: str, user_message: str) -> tuple[str, float]:
        t0 = time.perf_counter()
        try:
            response = self.client.messages.create(
                model=CLAUDE_MODEL,
                max_tokens=16384,
                system=system_prompt,
                messages=[{"role": "user", "content": user_message}],
            )
        except Exception as e:
            logger.error("[script_gen] │  Claude API call FAILED: %s", e)
            raise
        elapsed = time.perf_counter() - t0
        logger.info("[script_gen] │  Claude API response in %.1fs", elapsed)
        logger.info(
            "[script_gen] │  Usage: input=%d tokens, output=%d tokens",
            response.usage.input_tokens,
            response.usage.output_tokens,
        )
        logger.info("[script_gen] │  Stop reason: %s", response.stop_reason)
        return response.content[0].text, elapsed

    def _validate_script_quality(self, script_data: dict, personality=None) -> list[str]:
        errors: list[str] = []
        scenes = script_data.get("scenes") or []
        if len(scenes) < 4:
            errors.append("Need at least 4 scenes; target 5-7 for 1 minute+.")
            return errors

        # --- Narration quality checks ---
        for idx, scene in enumerate(scenes):
            narration = (scene.get("narration_text") or "").strip()
            word_count = len(narration.split())
            if word_count < 40:
                errors.append(
                    f"Scene {idx+1} narration_text too short ({word_count} words). "
                    "Must be 3-5 sentences (60-120 words) to fill the scene duration."
                )
            if idx == 0 and personality and hasattr(personality, "analogy_domain"):
                # Scene 0 should reference the character's analogy domain.
                # Split multi-word phrases into individual words so "game strategy"
                # also matches "game" or "strategy" on their own.
                domain_phrases = personality.analogy_domain.lower().split(", ")
                domain_words: set[str] = set()
                for phrase in domain_phrases:
                    domain_words.add(phrase)  # full phrase match
                    domain_words.update(phrase.split())  # individual words
                narration_lower = narration.lower()
                if not any(kw in narration_lower for kw in domain_words):
                    errors.append(
                        f"Scene 1 narration must open with an analogy from the character's "
                        f"domain ({personality.analogy_domain}). Use a hook that connects "
                        f"the topic to {personality.display_name}'s world."
                    )

        total_duration = 0.0
        has_graph = False
        has_transform_steps = False
        has_non_text_anim = False
        for idx, scene in enumerate(scenes):
            duration = float(scene.get("duration_hint_seconds", 0) or 0)
            total_duration += duration
            code = scene.get("manim_code") or ""
            stype = str(scene.get("manim_scene_type") or "").lower()
            if stype == "graph":
                has_graph = True
            if "Transform" in code:
                has_transform_steps = True
            if any(token in code for token in ("Axes(", "NumberPlane(", "Circle(", "Arrow(", "Transform", "Create(", "plot(")):
                has_non_text_anim = True

            if len(code) < 400:
                errors.append(f"Scene {idx+1} manim_code too short.")
            play_calls = len(re.findall(r"\bself\.play\(", code))
            if play_calls < 4:
                errors.append(f"Scene {idx+1} needs more animations (>=4 self.play calls).")

            # Catch ManimGL patterns that would crash ManimCE
            if "from manimlib import" in code and "from manim import" not in code:
                errors.append(f"Scene {idx+1}: uses 'from manimlib import' — MUST use 'from manim import *'.")
            if re.search(r'\bShowCreation\(', code):
                errors.append(f"Scene {idx+1}: uses ShowCreation() — MUST use Create().")
            if re.search(r'\.get_graph\(', code):
                errors.append(f"Scene {idx+1}: uses .get_graph() — MUST use .plot().")

            # Crash-prone patterns (engine-agnostic)
            if re.search(r'from\s+manim_\w+\s+import', code):
                errors.append(f"Scene {idx+1}: imports a manim plugin — only manim and numpy allowed.")
            # Unguarded division in graph lambdas
            if re.search(r'lambda\s+\w\s*:\s*[^,\n]*/\s*\w(?!\s*if)', code):
                errors.append(f"Scene {idx+1}: unguarded division in lambda — guard with abs(x) > 0.01.")
            # Missing final cleanup
            if "FadeOut(m) for m in self.mobjects" not in code:
                errors.append(f"Scene {idx+1}: missing final FadeOut cleanup — add self.play(*[FadeOut(m) for m in self.mobjects]).")

            # Text density: flag scenes with many Text/MathTex creates
            # without enough intermediate FadeOut calls to clear the screen.
            # The bulk cleanup pattern `FadeOut(m) for m in self.mobjects`
            # counts as clearing all objects, so we count those separately.
            text_creates = len(re.findall(r'\b(?:Text|MathTex|Tex)\s*\(', code))
            bulk_fadeouts = len(re.findall(r'FadeOut\(m\)\s+for\s+m\s+in\s+self\.mobjects', code))
            individual_fadeouts = len(re.findall(r'\bFadeOut\s*\(', code)) - bulk_fadeouts
            # Each bulk FadeOut clears everything, so it resets the "live" count.
            # We only flag if there are too many text objects without intermediate cleanup.
            if text_creates > 7 and individual_fadeouts < 2 and bulk_fadeouts < 2:
                errors.append(
                    f"Scene {idx+1}: creates {text_creates} text objects but only "
                    f"{individual_fadeouts} intermediate FadeOut calls. Add FadeOut between "
                    "content groups to prevent overlap (e.g., clear non-title elements "
                    "before introducing new content)."
                )

        # Count scenes with visual structures (not just stacked Text)
        visual_structure_count = 0
        for scene in scenes:
            code = scene.get("manim_code") or ""
            has_visual = any(token in code for token in (
                "Arrow(", "RoundedRectangle(", "Square(", "Circle(",
                "Axes(", "NumberPlane(", "Dot(", "Line(", "Brace(",
                "SurroundingRectangle(", "Polygon(", "RegularPolygon(",
                "plot(", "VGroup(",
            ))
            if has_visual:
                visual_structure_count += 1

        if total_duration < 55:
            errors.append(f"Total duration too short ({total_duration:.1f}s). Target >= 60s.")
        if not has_graph:
            errors.append("Missing graph scene with Axes and plotted functions.")
        if not has_transform_steps:
            errors.append("Missing equation/derivation scene with Transform steps.")
        if not has_non_text_anim:
            errors.append("Scenes are text-only; must include visual objects/animations.")
        if visual_structure_count < 3:
            errors.append(
                f"Only {visual_structure_count} scenes have visual structures (trees, tables, "
                "diagrams, graphs). Need at least 3. Convert text-only scenes into visual diagrams."
            )

        return errors

    def _build_system_prompt(
        self,
        personality,
        difficulty_instruction: str,
        live_manim_docs: str = "",
    ) -> str:
        live_docs_section = ""
        if live_manim_docs:
            live_docs_section = f"""
================================================================================
SUPPLEMENTARY MANIM DOCS (from Context7 — ManimCE documentation)
================================================================================
These docs are from Manim Community Edition, which is the engine you are using.
The MANIMCE API REFERENCE above is the PRIMARY source of truth for API rules.
Use these supplementary docs for understanding class hierarchies and patterns.
================================================================================
{live_manim_docs}
================================================================================
"""

        return f"""\
You are an expert educational animation developer producing 3Blue1Brown-quality \
video scenes using ManimCE (Manim Community Edition). You generate COMPLETE, \
RUNNABLE Python code for each scene — not just parameters.

CHARACTER PERSONA:
- Name: {personality.display_name}
- Tone: {personality.tone}
- Catchphrases: {', '.join(personality.catchphrases)}
- Analogy Domain: {personality.analogy_domain}

Write narration in this character's voice. Use their catchphrases naturally.

=== NARRATION RULES (MANDATORY) ===
1. ANALOGY HOOK (Scene 0 ONLY): Open Scene 0 with a character-specific analogy
   from the character's analogy domain ({personality.analogy_domain}).
   Example for LeBron: "Think of derivatives like reading a defense — you need
   to see what's changing and react in real time."
   After Scene 0, DROP the extended analogy and teach the actual content
   directly. Keep the character's tone, catchphrases, and personality throughout
   ALL scenes, but do NOT force analogies into every scene.

2. CONTINUOUS FLOW: Narration must flow as a continuous lecture. Each scene's
   narration_text should pick up where the previous scene left off. Use
   transition phrases like "Now that we understand X, let's look at Y" or
   "Building on that idea..." between scenes. There should be NO dead air,
   no abrupt topic switches, and no repeated introductions.

3. NARRATION LENGTH: Each scene's narration_text MUST be 3-5 sentences
   (60-120 words). The narration should fill the entire scene duration at
   ~150 words per minute. For a 30-second scene, write ~75 words of narration.
   NEVER leave narration_text shorter than 40 words.

4. CHARACTER VOICE: The narration must sound like the character is personally
   explaining the topic. It should NOT sound like a generic textbook or
   Wikipedia article. Use the character's catchphrases, tone, and personality
   consistently.

DIFFICULTY: {difficulty_instruction}

{MANIMCE_REFERENCE}
{live_docs_section}

=== OUTPUT FORMAT ===
Respond with ONLY valid JSON (no markdown fences, no extra text):
{{
    "title": "Catchy educational title",
    "total_scenes": <number>,
    "scenes": [
        {{
            "scene_index": 0,
            "narration_text": "What the character says during this scene (2-4 sentences, concept-focused, NOT describing the animation)",
            "manim_scene_type": "equation|graph|diagram|concept_reveal|geometry|summary",
            "manim_parameters": {{}},
            "duration_hint_seconds": 30,
            "character_action": "talking",
            "manim_code": "from manim import *\\nimport numpy as np\\n\\nclass Scene000(Scene):\\n    def construct(self):\\n        ..."
        }}
    ],
    "intro_text": "Engaging introduction",
    "outro_text": "Memorable closing"
}}

=== CRITICAL: manim_code FIELD ===
For EVERY scene, you MUST provide a "manim_code" field containing COMPLETE, \
RUNNABLE ManimCE Python code. Each scene's code:

1. MUST start with: from manim import *
2. MUST import numpy: import numpy as np
3. MUST define exactly ONE Scene subclass named Scene{{scene_index:03d}}
   (e.g. Scene000, Scene001, Scene002, ...)
4. MUST implement construct(self) with rich animations
5. MUST be 40-80+ lines of actual animation code (NOT just text display)
6. MUST produce a video of AT LEAST the duration_hint_seconds length
   (use self.wait() to pad timing — add waits after each animation block)
7. MUST use self.play() with explicit run_time for every animation
8. MUST use self.wait(2) to self.wait(5) between animation groups

=== TEXT & MATH RENDERING (ManimCE) ===
- Use MathTex(r"...") for ALL mathematical expressions (equations, formulas, variables).
  MathTex renders beautiful LaTeX. ALWAYS use raw strings: r"..."
  MathTex() accepts color= and font_size= as constructor args:
    MathTex(r"x^2 + 1 = 0", color=BLUE, font_size=36)
- Use Text("...") for titles, labels, prose, and non-math content.
  Text() DOES accept color= and font_size= as constructor args.
- Use TransformMatchingTex(old, new) to animate between LaTeX equations.
- For step-by-step derivations: create separate MathTex objects and use
  TransformMatchingTex between them (preferred) or ReplacementTransform.
- Keep MathTex strings simple — avoid overly complex nested environments.

=== VIDEO STRUCTURE (MANDATORY) ===
- Generate 5 to 7 scenes for a video totaling 1.5 to 3 minutes.
- Scene 0: Concept introduction (20-30 seconds) — title card + key concepts
- Scenes 1-4: Core teaching content (30-45 seconds each) — equations, graphs, \
  diagrams, step-by-step builds
- Last scene: Summary/recap (20-30 seconds) — key takeaways
- EVERY video MUST include at least:
  * One scene with Axes and plotted functions (use axes.plot())
  * One scene with step-by-step equation transforms using MathTex
  * Rich animations in every scene (no static text-only screens)

=== SPATIAL SAFETY — CRITICAL (content MUST stay visible) ===
USE THE GRID LAYOUT SYSTEM above. Title at UP * 3.2, content at DOWN * 0.3.
NEVER hard-code absolute shifts. Use named grid positions only.

Additional rules:
1. When stacking with .arrange(DOWN), limit to 4-5 items max, then
   .move_to(DOWN * 0.3) to center the group in the main area.
2. For Axes: axes.move_to(DOWN * 0.3) to keep below title.
   Use x_length and y_length to control Axes size, then .move_to(DOWN * 0.3)
3. VGroup with many elements: cap with .set_height(5.5).
4. Side-by-side layouts: .arrange(RIGHT, buff=1.0), cap with .set_width(12).
5. NEVER .shift() with magnitude > 3.5 from ORIGIN.
6. Bar charts: max bar height of 4.0 units. After building any VGroup of bars/rectangles:
     group.set_height(min(group.get_height(), 5.0)).move_to(DOWN * 0.3)
7. Post-build height safety for ANY visual group:
     if group.get_height() > 5.5:
         group.set_height(5.5).move_to(DOWN * 0.3)
8. TEXT WIDTH SAFETY (MANDATORY): After creating ANY Text or MathTex element,
   ALWAYS cap its width to prevent overflow:
     text.set_width(min(text.width, 10.0))
   This is especially critical for long labels, equations, and explanations.

=== ANIMATION QUALITY RULES ===
1. PROGRESSIVE BUILDUP: Each element appears one at a time with self.play().
   Never dump everything on screen at once.
2. MEANINGFUL TRANSITIONS: Use self.play(FadeOut(...)) to clear before new content.
   Clear the screen between major content blocks to avoid clutter.
3. COLOR CODING: BLUE=primary, YELLOW=highlight, GREEN=result, RED=important.
4. TIMING: Every self.play() MUST have run_time=1.5 to 3 seconds.
   Add self.wait(2) after important reveals.
5. DIM PREVIOUS ELEMENTS: When introducing new content, dim old content with
   self.play(prev.animate.set_opacity(0.3)) — restore with set_opacity(1.0).
6. For graphs: use axes.plot(), add tracing dots, show tangent lines.
   Never a bare static plot.
7. For equations: use MathTex + TransformMatchingTex or ReplacementTransform.
   Highlight changing parts with .set_color().
8. Use SurroundingRectangle, Brace, Arrow for annotations.
9. Each scene should feel like a mini-lesson — build up, explain, emphasize.
10. Use LaggedStart with lag_ratio=0.2 for revealing lists of items.
    NEVER FadeIn an entire VGroup at once.

=== ARRAYS, BOXES & LABELED CELLS — ALIGNMENT RULES (CRITICAL) ===
When drawing arrays, hash tables, stacks, grids, or any "box with a label inside":

1. ALWAYS create each cell as a VGroup(rect, label) so they stay locked together:
     cell_rect = Square(side_length=1.0, color=WHITE)
     cell_label = Text("5", font_size=32).move_to(cell_rect.get_center())
     cell = VGroup(cell_rect, cell_label)
   NEVER position the label separately with .shift() or .next_to() — it WILL drift.

2. Font size must be proportional to the box. NEVER use font_size < 24.

3. Build the full array as a VGroup of cell VGroups, then arrange once:
     cells = VGroup(*[make_cell(v) for v in values])
     cells.arrange(RIGHT, buff=0).move_to(ORIGIN)

4. To highlight a cell, use Indicate(cell) or cell_rect.animate.set_fill(YELLOW, 0.3).

5. Helper pattern for array scenes (copy this approach):
     def make_cell(value, size=1.0):
         rect = Square(side_length=size, color=WHITE)
         label = Text(str(value), font_size=32).move_to(rect.get_center())
         return VGroup(rect, label)
   Then: array_group = VGroup(*[make_cell(v) for v in [3, 7, 1, 9, 2]])
         array_group.arrange(RIGHT, buff=0).move_to(ORIGIN)

=== EXAMPLE: Graph scene with Axes — Graph Layout (ManimCE) ===
```
from manim import *
import numpy as np

class Scene001(Scene):
    def construct(self):
        # TITLE at grid TITLE_POS
        title = Text("Understanding Derivatives", font_size=42)
        title.move_to(UP * 3.2)
        self.play(Write(title), run_time=2)
        self.wait(1)

        # AXES at grid MAIN_AREA
        axes = Axes(
            x_range=[-3, 3, 1], y_range=[-1, 9, 2],
            x_length=10, y_length=5,
            tips=True,
        )
        axes.move_to(DOWN * 0.3)
        x_lab = axes.get_x_axis_label("x")
        y_lab = axes.get_y_axis_label("f(x)")
        self.play(Create(axes), Write(x_lab), Write(y_lab), run_time=2)
        self.wait(1)

        graph = axes.plot(lambda x: x**2, color=BLUE, x_range=[-2.8, 2.8])
        graph_label = MathTex(r"f(x) = x^2", color=BLUE, font_size=28)
        graph_label.next_to(axes.c2p(2, 4), RIGHT)
        self.play(Create(graph), run_time=3)
        self.play(Write(graph_label), run_time=1)
        self.wait(2)

        x_val = 1
        slope = 2 * x_val
        tangent = axes.plot(
            lambda x: slope * (x - x_val) + x_val**2,
            color=YELLOW, x_range=[-0.5, 2.5],
        )
        dot = Dot(axes.c2p(x_val, x_val**2), color=YELLOW)
        slope_label = MathTex(r"f'(1) = 2", color=YELLOW, font_size=28)
        slope_label.next_to(dot, UR, buff=0.3)

        # Dim the graph while showing tangent
        self.play(graph.animate.set_opacity(0.3), run_time=0.5)
        self.play(Create(dot), run_time=1)
        self.play(Create(tangent), Write(slope_label), run_time=2)
        self.wait(2)
        self.play(graph.animate.set_opacity(1.0), run_time=0.5)
        self.wait(2)

        # CLEANUP — mandatory
        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
        self.wait(1)
```

=== EXAMPLE: Equation derivation — Full Center layout (ManimCE) ===
```
from manim import *
import numpy as np

class Scene002(Scene):
    def construct(self):
        # TITLE at grid TITLE_POS
        title = Text("Solving Quadratics", font_size=42)
        title.move_to(UP * 3.2)
        self.play(Write(title), run_time=2)
        self.wait(1)

        # Equations at grid MAIN_AREA
        step1 = MathTex(r"x^2 - 5x + 6 = 0", color=BLUE, font_size=40)
        step1.move_to(DOWN * 0.3)
        self.play(Write(step1), run_time=2)
        self.wait(2)

        step2 = MathTex(r"(x - 2)(x - 3) = 0", color=GREEN, font_size=40)
        step2.move_to(DOWN * 0.3)
        self.play(TransformMatchingTex(step1, step2), run_time=2)
        self.wait(2)

        step3 = MathTex(r"x = 2 \\quad \\text{{or}} \\quad x = 3", color=YELLOW, font_size=40)
        step3.move_to(DOWN * 0.3)
        self.play(TransformMatchingTex(step2, step3), run_time=2)
        box = SurroundingRectangle(step3, color=YELLOW, buff=0.25)
        self.play(Create(box), run_time=1.5)
        self.wait(3)

        # TRANSITION: clear non-title elements for second idea
        self.play(*[FadeOut(m) for m in self.mobjects if m is not title], run_time=1)

        # Verification at grid MAIN_AREA (Vertical Stack)
        check_title = Text("Verification:", font_size=32)
        check1 = MathTex(r"(2)^2 - 5(2) + 6 = 0 \\checkmark", color=GREEN, font_size=32)
        check2 = MathTex(r"(3)^2 - 5(3) + 6 = 0 \\checkmark", color=GREEN, font_size=32)
        checks = VGroup(check_title, check1, check2).arrange(DOWN, buff=0.4)
        checks.move_to(DOWN * 0.3)

        self.play(Write(check_title), run_time=1.5)
        self.play(Write(check1), run_time=2)
        self.play(Write(check2), run_time=2)
        self.wait(3)

        # CLEANUP — mandatory
        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
        self.wait(1)
```

=== EXAMPLE: Concept reveal — Vertical Stack layout (ManimCE) ===
```
from manim import *
import numpy as np

class Scene003(Scene):
    def construct(self):
        # TITLE at grid TITLE_POS
        title = Text("Key Principles of Evolution", font_size=44, weight=BOLD)
        title.move_to(UP * 3.2)
        self.play(Write(title), run_time=2)
        self.wait(1)

        # Build concept cards at grid MAIN_AREA (Vertical Stack)
        concepts = ["Natural Selection", "Genetic Variation", "Adaptation"]
        colors = [BLUE, GREEN, TEAL]
        cards = []
        for text, col in zip(concepts, colors):
            card_bg = RoundedRectangle(width=6, height=1.0, corner_radius=0.15, color=col)
            card_text = Text(text, font_size=30).move_to(card_bg.get_center())
            cards.append(VGroup(card_bg, card_text))

        card_group = VGroup(*cards).arrange(DOWN, buff=0.4)
        card_group.move_to(DOWN * 0.3)  # grid MAIN_AREA

        # Progressive reveal with dimming
        self.play(FadeIn(cards[0], shift=UP * 0.3), run_time=1.5)
        self.wait(1)

        self.play(cards[0].animate.set_opacity(0.3), run_time=0.5)
        self.play(FadeIn(cards[1], shift=UP * 0.3), run_time=1.5)
        self.wait(1)

        self.play(cards[1].animate.set_opacity(0.3), run_time=0.5)
        self.play(FadeIn(cards[2], shift=UP * 0.3), run_time=1.5)
        self.wait(1)

        # Restore all and emphasize
        self.play(*[c.animate.set_opacity(1.0) for c in cards], run_time=1)
        self.play(Indicate(cards[2], color=YELLOW), run_time=1.5)

        # Add connecting arrow
        arrow = Arrow(cards[0].get_bottom(), cards[2].get_top(), color=WHITE, buff=0.15)
        self.play(GrowArrow(arrow), run_time=1.5)
        self.wait(3)

        # CLEANUP — mandatory
        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
        self.wait(1)
```

Each scene is ~30 seconds of content. Your scenes should be similar or longer.
"""

    def _build_user_message(self, extracted_text: str, user_prompt: Optional[str]) -> str:
        message = f"""\
Create an educational video with 5-7 scenes based on this source material.
Analyze the material carefully — identify the key concepts, mathematical \
relationships, functions, and problems, then create scenes that VISUALLY \
teach them with rich Manim animations.

--- SOURCE MATERIAL ---
{extracted_text}
--- END SOURCE MATERIAL ---

REQUIREMENTS:
1. Generate 5-7 scenes with complete ManimCE manim_code for each
2. Total video duration: 1.5 to 3 minutes (sum of all duration_hint_seconds)
3. Each scene must have 30-60 seconds of content
4. Include at least one graph scene with Axes and axes.plot()
5. Include at least one equation scene with step-by-step transforms using MathTex
6. Last scene must be a summary/recap
7. Every scene must have rich, multi-step animations (not just text)
8. Use self.wait() generously between animation groups
9. All code MUST use: from manim import * (NOT from manimlib import *)
10. Use Create() NOT ShowCreation(). Use MathTex() for math expressions.
"""
        if user_prompt:
            message += f"\nAdditional instructions: {user_prompt}\n"

        message += "\nRespond with ONLY the JSON object. No markdown fences."
        return message

    def _parse_response(self, response_text: str) -> dict:
        text = response_text.strip()
        if text.startswith("```json"):
            text = text[7:]
        if text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

        try:
            return json.loads(text)
        except json.JSONDecodeError as e:
            logger.error("[script_gen] Failed to parse JSON: %s", e)
            logger.error("[script_gen] Response text: %s", text[:1000])
            raise ValueError(f"LLM did not return valid JSON: {e}")
