"""Service for generating educational scripts using the Anthropic Claude API.

Each scene gets complete, runnable Manim Community Edition (ManimCE) Python
code generated by the LLM.  This replaces the old template-based approach
with direct LLM code generation — matching the arxivisual architecture that
produces 3Blue1Brown-quality animations.
"""

import asyncio
import json
import logging
import re
import time
from typing import Optional

import anthropic

from shared.contracts.character_schema import CHARACTER_PERSONALITIES
from shared.contracts.enums import Character, Difficulty
from shared.contracts.pipeline_schema import GeneratedScript

from ..config import settings
from .context7_docs import get_manim_docs

logger = logging.getLogger(__name__)

CLAUDE_MODEL = "claude-sonnet-4-20250514"

DIFFICULTY_INSTRUCTIONS: dict[Difficulty, str] = {
    Difficulty.BEGINNER: (
        "Explain concepts at a beginner level. Use simple language, avoid jargon, "
        "and break down ideas into the most fundamental building blocks."
    ),
    Difficulty.INTERMEDIATE: (
        "Explain at an intermediate level. Use some technical terms "
        "but always briefly clarify them. Build on foundational knowledge."
    ),
    Difficulty.ADVANCED: (
        "Explain at an advanced level. Use proper technical terminology, "
        "explore nuances, edge cases, and deeper implications."
    ),
}

# Built-in Manim CE reference so the LLM always has a baseline even if
# Context7 is unavailable.
MANIM_CE_REFERENCE = r"""
MANIM COMMUNITY EDITION — QUICK API REFERENCE
==============================================
Import: from manim import *

TEXT & MATH MOBJECTS:
  Text("hello", font_size=36)           — titles, labels, prose (Pango/Cairo)
  MathTex(r"x^2 + 1 = 0")              — LaTeX math expressions (beautiful)
  MathTex(r"\frac{d}{dx} x^2 = 2x")   — fractions, derivatives, integrals
  MathTex(r"\int_0^1 x\,dx = \frac{1}{2}")  — integrals with limits
  Tex(r"Hello \textbf{world}")          — LaTeX text mode
  ALWAYS use raw strings r"..." for MathTex/Tex content.
  Use Text() for plain titles/labels, MathTex() for equations and formulas.

SHAPES & GEOMETRY:
  Axes(x_range=[a,b,s], y_range=[c,d,s], x_length=8, y_length=5)
  NumberPlane(x_range, y_range)
  NumberLine(x_range, length)
  Dot(point), Line(start, end), Arrow(start, end)
  Circle(radius), Square(side_length), Rectangle(width, height)
  RoundedRectangle(corner_radius, width, height)
  VGroup(mob1, mob2, ...)               — group mobjects together
  SurroundingRectangle(mob, color, buff)
  Brace(mob, direction)
  DashedLine(start, end)
  Polygon(*points), RegularPolygon(n)
  Arc(angle), AnnularSector(inner_radius, outer_radius, angle)

POSITIONING:
  mob.to_edge(UP/DOWN/LEFT/RIGHT, buff=0.5)
  mob.to_corner(UL/UR/DL/DR, buff=0.5)
  mob.next_to(other, DOWN, buff=0.3)
  mob.move_to(point_or_mob)
  mob.shift(RIGHT * 2 + UP * 1)
  VGroup(...).arrange(DOWN, buff=0.4)
  VGroup(...).arrange_in_grid(rows, cols, buff=0.3)

DIRECTIONS: UP, DOWN, LEFT, RIGHT, UL, UR, DL, DR, ORIGIN

ANIMATIONS:
  Write(mob), Create(mob), FadeIn(mob), FadeOut(mob)
  Transform(src, dst), ReplacementTransform(src, dst)
  TransformMatchingTex(old_tex, new_tex) — animate matching LaTeX parts
  Indicate(mob, color=YELLOW, scale_factor=1.2)
  GrowFromCenter(mob), GrowArrow(arrow)
  MoveAlongPath(dot, path)
  LaggedStart(*anims, lag_ratio=0.15)
  AnimationGroup(*anims)
  Circumscribe(mob, color)
  Flash(point, color)

PLAY:
  self.play(Create(mob), run_time=2)
  self.play(mob.animate.shift(RIGHT*2), run_time=1.5)
  self.play(mob.animate.set_color(YELLOW))
  self.wait(2)

AXES METHODS:
  graph = axes.plot(lambda x: x**2, color=BLUE, x_range=[-3,3])
  label = MathTex(r"x^2", font_size=24, color=BLUE).next_to(axes.c2p(2, 4), RIGHT)
  area = axes.get_area(graph, x_range=[0,2], color=BLUE, opacity=0.3)
  dot = Dot(axes.c2p(x, y))   — coordinate to point

COLORS:
  BLUE, BLUE_A/B/C/D/E, RED, RED_A-E, GREEN, GREEN_A-E,
  YELLOW, YELLOW_A-E, GOLD, GOLD_A-E, TEAL, TEAL_A-E,
  PURPLE, PURPLE_A-E, MAROON, MAROON_A-E, ORANGE, PINK,
  GREY, GREY_A-D, WHITE, BLACK

SCENE CLASS:
  class MyScene(Scene):
      def construct(self):
          ...

================================================================================
INSTALLED MANIM PLUGINS — USE WHEN TOPIC MATCHES
================================================================================
These plugins are installed and available. Use them when the source material
matches their domain. Each requires its OWN import line IN ADDITION TO
"from manim import *".

── PHYSICS (manim-physics) ─────────────────────────────────────────────────────
  Import: from manim_physics import *
  When: Electromagnetism, mechanics, optics, waves, pendulums
  Key classes:
    SpaceScene        — base scene for rigid-body physics simulations
    Charge(magnitude, point)  — positive/negative electric charges
    ElectricField(*charges)   — visualize electric field lines
    MagneticField(Wire(...))  — visualize magnetic field around a wire
    Wire(start, end, current) — current-carrying wire
    Pendulum(length, initial_theta)          — single pendulum simulation
    MultiPendulum(lengths, initial_thetas)   — double/multi-pendulum
    LinearWave, RadialWave, StandingWave     — wave animations
    Ray(start, end), Lens(focal_length)      — geometric optics
  Note: Physics scenes that simulate motion should subclass SpaceScene
  instead of Scene and call self.make_rigid_body(mob) / self.make_static_body.

── CHEMISTRY (manim-chemistry) ─────────────────────────────────────────────────
  Import: from manim_chemistry import *
  When: Molecular structures, chemical formulas, periodic table, orbitals
  Key classes:
    BohrAtom(e=<num_electrons>)              — Bohr model atom visualization
    Element(atomic_number)                    — periodic table element card
    PeriodicTable()                           — full periodic table display
    GraphMolecule(from_mol_file=...)          — 2D molecule from MOL file
    MMoleculeObject, MAtomObject              — molecular structure components
    ChemicalFormula(*formula_parts)           — formatted chemical formula
    NamedFormula(formula, name)               — formula with name label
    DoubleBond, TripleBond, SimpleBond        — bond visualizations
    Orbital(n, l)                             — electron orbital shapes
    ThreeDMolecule                            — 3D molecule rendering

── DATA STRUCTURES (manim-dsa) ─────────────────────────────────────────────────
  Import: from manim_dsa import *
  When: Arrays, stacks, graphs, algorithm visualization, CS concepts
  Key classes:
    MArray(arr=[1,2,3,...])                   — animated array visualization
    MStack()                                  — animated stack (push/pop)
    MGraph(vertices, edges)                   — graph/tree visualization
  Styles: MArrayStyle, MStackStyle, MGraphStyle for customization.

── CIRCUITS (manim-circuit) ────────────────────────────────────────────────────
  Import: from manim_circuit import *
  When: Electrical circuits, electronics, circuit analysis
  Key classes:
    Circuit()                                — circuit canvas
    Resistor(start, end, value)              — resistor component
    Capacitor(start, end, value)             — capacitor component
    Inductor(start, end, value)              — inductor component
    VoltageSource(start, end, value)         — voltage source
    CurrentSource(start, end, value)         — current source
    Ground(point)                            — ground symbol
    Node(point)                              — circuit node
    Opamp(...)                               — operational amplifier

── AUTOMATA (manim-automata) ───────────────────────────────────────────────────
  Import: from manim_automata import *
  When: Finite automata, DFA, NFA, Turing machines, formal languages
  Key classes:
    ManimDeterminsticFiniteAutomaton(...)     — DFA visualization
    ManimNonDeterminsticFiniteAutomaton(...)  — NFA visualization
    ManimPushDownAutomaton(...)               — PDA visualization
    ManimState, ManimTransition, State       — automaton building blocks

── CODE BLOCKS (manim-code-blocks-redux) ───────────────────────────────────────
  Import: from manim_code_blocks import *
  When: Displaying source code with syntax highlighting
  Note: Creates syntax-highlighted code blocks as Manim mobjects.

── CAD DRAWING (manim-CAD-Drawing-Utils) ───────────────────────────────────────
  Import: from manim_cad_drawing_utils import *
  When: Technical/engineering diagrams with dimensions and annotations
  Key classes:
    Linear_Dimension(start, end)             — dimension line with measurement
    Angle_Dimension_3point(p1, vertex, p2)   — angle dimension
    Round_Corners(mob, radius)               — round corners on shapes
    Pointer_To_Mob(mob, label)               — pointer/callout annotation
    Hatch_lines(mob)                         — engineering hatch fill
"""


def _fetch_live_manim_docs(source_text: str) -> str:
    """Fetch live Manim docs from Context7 based on the source material."""
    topic = "manim Scene Text Axes NumberPlane Create FadeIn Write Transform animations plot VGroup MathTex physics chemistry circuit automata data structures"
    logger.info("[script_gen] Fetching live Manim docs from Context7 (topic: %s)", topic)
    try:
        docs = asyncio.run(get_manim_docs(topic=topic, max_tokens=5000))
        if docs:
            logger.info("[script_gen] Context7 returned %d chars of live Manim docs", len(docs))
            return docs
        logger.warning("[script_gen] Context7 returned empty docs")
    except Exception as exc:
        logger.warning("[script_gen] Context7 fetch failed: %s — using built-in reference", exc)
    return ""


class ScriptGenerator:
    """Generates structured educational scripts with complete Manim code per scene."""

    def __init__(self) -> None:
        self.client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    def generate(
        self,
        extracted_text: str,
        character: Character,
        difficulty: Difficulty,
        user_prompt: Optional[str] = None,
    ) -> GeneratedScript:
        logger.info("[script_gen] ┌─ Generating script")
        logger.info("[script_gen] │  Character: %s", character.value)
        logger.info("[script_gen] │  Difficulty: %s", difficulty.value)
        logger.info("[script_gen] │  Source text: %d chars", len(extracted_text))
        logger.info("[script_gen] │  Model: %s", CLAUDE_MODEL)

        personality = CHARACTER_PERSONALITIES[character]
        difficulty_instruction = DIFFICULTY_INSTRUCTIONS[difficulty]

        t0 = time.perf_counter()
        live_docs = _fetch_live_manim_docs(extracted_text)
        docs_elapsed = time.perf_counter() - t0
        logger.info("[script_gen] │  Context7 fetch: %.1fs, %d chars", docs_elapsed, len(live_docs))

        system_prompt = self._build_system_prompt(
            personality, difficulty_instruction, live_docs
        )
        user_message = self._build_user_message(extracted_text, user_prompt)

        logger.info("[script_gen] │  System prompt: %d chars", len(system_prompt))
        logger.info("[script_gen] │  User message: %d chars", len(user_message))

        response_text, api_elapsed = self._request_script(system_prompt, user_message)
        logger.info("[script_gen] │  Response: %d chars", len(response_text))
        logger.info("[script_gen] │  Response preview: %.500s...", response_text)

        script_data = self._parse_response(response_text)

        quality_errors = self._validate_script_quality(script_data)
        if quality_errors:
            logger.warning("[script_gen] │  First draft quality issues: %s", quality_errors)
            feedback = (
                "Regenerate the full JSON and fix ALL issues:\n- "
                + "\n- ".join(quality_errors)
            )
            retry_user_message = f"{user_message}\n\n{feedback}"
            response_text, retry_elapsed = self._request_script(system_prompt, retry_user_message)
            api_elapsed += retry_elapsed
            script_data = self._parse_response(response_text)
            quality_errors = self._validate_script_quality(script_data)
            if quality_errors:
                logger.warning(
                    "[script_gen] │  Quality issues remain after retry: %s. Continuing with best effort.",
                    quality_errors,
                )

        script_data["character"] = character.value
        script_data["difficulty"] = difficulty.value
        script_data["language"] = "en"

        script = GeneratedScript(**script_data)
        logger.info("[script_gen] │  Title: %s", script.title)
        logger.info("[script_gen] │  Total scenes: %d", script.total_scenes)
        for i, s in enumerate(script.scenes):
            has_code = bool(s.manim_code)
            code_len = len(s.manim_code) if s.manim_code else 0
            logger.info(
                "[script_gen] │  Scene %d: type=%s, duration=%.0fs, has_code=%s (%d chars)",
                i + 1, s.manim_scene_type, s.duration_hint_seconds, has_code, code_len,
            )
        logger.info("[script_gen] └─ Script generation complete (%.1fs total)", docs_elapsed + api_elapsed)
        return script

    def _request_script(self, system_prompt: str, user_message: str) -> tuple[str, float]:
        t0 = time.perf_counter()
        try:
            response = self.client.messages.create(
                model=CLAUDE_MODEL,
                max_tokens=16384,
                system=system_prompt,
                messages=[{"role": "user", "content": user_message}],
            )
        except Exception as e:
            logger.error("[script_gen] │  Claude API call FAILED: %s", e)
            raise
        elapsed = time.perf_counter() - t0
        logger.info("[script_gen] │  Claude API response in %.1fs", elapsed)
        logger.info(
            "[script_gen] │  Usage: input=%d tokens, output=%d tokens",
            response.usage.input_tokens,
            response.usage.output_tokens,
        )
        logger.info("[script_gen] │  Stop reason: %s", response.stop_reason)
        return response.content[0].text, elapsed

    def _validate_script_quality(self, script_data: dict) -> list[str]:
        errors: list[str] = []
        scenes = script_data.get("scenes") or []
        if len(scenes) < 4:
            errors.append("Need at least 4 scenes; target 5-7 for 1 minute+.")
            return errors

        total_duration = 0.0
        has_graph = False
        has_transform_steps = False
        has_non_text_anim = False
        for idx, scene in enumerate(scenes):
            duration = float(scene.get("duration_hint_seconds", 0) or 0)
            total_duration += duration
            code = scene.get("manim_code") or ""
            stype = str(scene.get("manim_scene_type") or "").lower()
            if stype == "graph":
                has_graph = True
            if "Transform" in code:
                has_transform_steps = True
            if any(token in code for token in ("Axes(", "NumberPlane(", "Circle(", "Arrow(", "Transform", "Create(")):
                has_non_text_anim = True

            if len(code) < 400:
                errors.append(f"Scene {idx+1} manim_code too short.")
            play_calls = len(re.findall(r"\bself\.play\(", code))
            if play_calls < 4:
                errors.append(f"Scene {idx+1} needs more animations (>=4 self.play calls).")

        if total_duration < 55:
            errors.append(f"Total duration too short ({total_duration:.1f}s). Target >= 60s.")
        if not has_graph:
            errors.append("Missing graph scene with Axes and plotted functions.")
        if not has_transform_steps:
            errors.append("Missing equation/derivation scene with Transform steps.")
        if not has_non_text_anim:
            errors.append("Scenes are text-only; must include visual objects/animations.")

        return errors

    def _build_system_prompt(
        self,
        personality,
        difficulty_instruction: str,
        live_manim_docs: str = "",
    ) -> str:
        live_docs_section = ""
        if live_manim_docs:
            live_docs_section = f"""
================================================================================
LIVE MANIM API REFERENCE (from Context7 — treat as PRIMARY source)
================================================================================
{live_manim_docs}
================================================================================
"""

        return f"""\
You are an expert educational animation developer producing 3Blue1Brown-quality \
video scenes using Manim Community Edition (ManimCE). You generate COMPLETE, \
RUNNABLE Python code for each scene — not just parameters.

CHARACTER PERSONA:
- Name: {personality.display_name}
- Tone: {personality.tone}
- Catchphrases: {', '.join(personality.catchphrases)}

Write narration in this character's voice. Use their catchphrases naturally.

DIFFICULTY: {difficulty_instruction}

{MANIM_CE_REFERENCE}
{live_docs_section}

=== OUTPUT FORMAT ===
Respond with ONLY valid JSON (no markdown fences, no extra text):
{{
    "title": "Catchy educational title",
    "total_scenes": <number>,
    "scenes": [
        {{
            "scene_index": 0,
            "narration_text": "What the character says during this scene (2-4 sentences, concept-focused, NOT describing the animation)",
            "manim_scene_type": "equation|graph|diagram|concept_reveal|geometry|summary",
            "manim_parameters": {{}},
            "duration_hint_seconds": 30,
            "character_action": "talking",
            "manim_code": "from manim import *\\n\\nclass Scene000(Scene):\\n    def construct(self):\\n        ..."
        }}
    ],
    "intro_text": "Engaging introduction",
    "outro_text": "Memorable closing"
}}

=== CRITICAL: manim_code FIELD ===
For EVERY scene, you MUST provide a "manim_code" field containing COMPLETE, \
RUNNABLE Manim Community Edition Python code. Each scene's code:

1. MUST start with: from manim import *
2. MUST define exactly ONE Scene subclass named Scene{{scene_index:03d}}
   (e.g. Scene000, Scene001, Scene002, ...)
3. MUST implement construct(self) with rich animations
4. MUST be 40-80+ lines of actual animation code (NOT just text display)
5. MUST produce a video of AT LEAST the duration_hint_seconds length
   (use self.wait() to pad timing — add waits after each animation block)
6. MUST use self.play() with explicit run_time for every animation
7. MUST use self.wait(2) to self.wait(5) between animation groups

=== TEXT & MATH RENDERING ===
- Use MathTex(r"...") for ALL mathematical expressions (equations, formulas, variables).
  MathTex renders beautiful LaTeX. ALWAYS use raw strings: r"..."
- Use Text("...") for titles, labels, prose, and non-math content.
- Use TransformMatchingTex(old, new) to animate between LaTeX equations.
- For step-by-step derivations: create separate MathTex objects and use
  ReplacementTransform or TransformMatchingTex between them.
- Keep MathTex strings simple — avoid overly complex nested environments.

=== VIDEO STRUCTURE (MANDATORY) ===
- Generate 5 to 7 scenes for a video totaling 1.5 to 3 minutes.
- Scene 0: Concept introduction (20-30 seconds) — title card + key concepts
- Scenes 1-4: Core teaching content (30-45 seconds each) — equations, graphs, \
  diagrams, step-by-step builds
- Last scene: Summary/recap (20-30 seconds) — key takeaways
- EVERY video MUST include at least:
  * One scene with Axes and plotted mathematical functions
  * One scene with step-by-step equation transforms using MathTex
  * Rich animations in every scene (no static text-only screens)

=== SPATIAL SAFETY — CRITICAL (content MUST stay visible) ===
The Manim frame is 14.2 units wide and 8 units tall, centered at ORIGIN.
Visible bounds: x in [-7.1, 7.1], y in [-4.0, 4.0].
SAFE bounds (with margin): x in [-6.0, 6.0], y in [-3.2, 3.2].

STRICT RULES to prevent content going off-screen:
1. Title goes to top: title.to_edge(UP, buff=0.5) — this is y ≈ 3.5. All other
   content MUST stay below y=2.8.
2. NEVER use .shift(DOWN * N) with N > 2.5 from center.
3. When stacking items vertically with .arrange(DOWN), limit to 4-5 items max
   and always call .move_to(ORIGIN) or .shift(DOWN * 0.3) on the group AFTER
   arranging, so the group is centered.
4. For Axes: use y_length=4.5 max and .shift(DOWN * 0.3) to keep below title.
5. Any VGroup with many elements: call .scale_to_fit_height(5.5) if it risks
   being taller than the frame.
6. ALWAYS use .to_edge() or .next_to() for positioning. AVOID absolute .shift()
   with large values.
7. For side-by-side layouts, use .arrange(RIGHT, buff=1.0) and ensure the group
   width stays under 12 units. Use .scale_to_fit_width(12) if needed.

=== PLUGIN USAGE (USE WHEN RELEVANT) ===
Manim plugins are installed. When the source material covers a domain that
matches a plugin, you SHOULD use it to create richer, more accurate visuals.
Rules:
1. ALWAYS keep "from manim import *" as the FIRST import.
2. Add plugin imports as ADDITIONAL lines: "from manim_physics import *" etc.
3. Only import plugins you actually use in that scene.
4. If a topic is about physics (E&M, waves, mechanics, optics) → use manim_physics.
5. If a topic is about chemistry (molecules, atoms, reactions, orbitals) → use manim_chemistry.
6. If a topic is about data structures or algorithms → use manim_dsa.
7. If a topic is about circuits or electronics → use manim_circuit.
8. If a topic is about automata, DFA/NFA, formal languages → use manim_automata.
9. If you want to show source code with highlighting → use manim_code_blocks.
10. For engineering/technical diagrams with dimensions → use manim_cad_drawing_utils.
11. If the topic does NOT match any plugin domain, stick to core Manim only.
12. You can MIX plugin objects with core Manim objects in the same scene.

=== ANIMATION QUALITY RULES ===
1. PROGRESSIVE BUILDUP: Each element appears one at a time with self.play().
   Never dump everything on screen at once.
2. MEANINGFUL TRANSITIONS: Use self.play(FadeOut(...)) to clear before new content.
   Clear the screen between major content blocks to avoid clutter.
3. COLOR CODING: BLUE=primary, YELLOW=highlight, GREEN=result, RED=important.
4. TIMING: Every self.play() MUST have run_time=1.5 to 3 seconds.
   Add self.wait(2) after important reveals.
5. For graphs: plot functions, add tracing dots, shade areas, show tangent lines.
   Never a bare static plot.
6. For equations: use MathTex + TransformMatchingTex or ReplacementTransform.
   Highlight changing parts with color.
7. Use SurroundingRectangle, Brace, Arrow for annotations.
8. Each scene should feel like a mini-lesson — build up, explain, emphasize.
9. Use geometric shapes (Circle, Square, Arrow, Polygon) to build diagrams.
   Combine shapes with Text labels for powerful visual explanations.

=== ARRAYS, BOXES & LABELED CELLS — ALIGNMENT RULES (CRITICAL) ===
When drawing arrays, hash tables, stacks, grids, or any "box with a label inside":

1. ALWAYS create each cell as a VGroup(rect, label) so they stay locked together:
     cell_rect = Square(side_length=1.0, color=WHITE)
     cell_label = Text("5", font_size=32).move_to(cell_rect.get_center())
     cell = VGroup(cell_rect, cell_label)
   NEVER position the label separately with .shift() or .next_to() — it WILL drift.

2. Font size must be proportional to the box.
   For a Square(side_length=1.0), use font_size=32-36.
   For a Square(side_length=0.8), use font_size=26-30.
   For a Rectangle(width=1.5, height=0.8), use font_size=28-32.
   NEVER use font_size < 24 inside a box — it becomes unreadable.

3. Build the full array as a VGroup of cell VGroups, then arrange once:
     cells = VGroup(*[make_cell(v) for v in values])
     cells.arrange(RIGHT, buff=0)     # horizontal array
     cells.arrange(DOWN, buff=0)      # vertical array/stack
   This guarantees uniform spacing with no drift.

4. Index labels go OUTSIDE the cell, using .next_to():
     idx = Text("0", font_size=20, color=GRAY).next_to(cell, DOWN, buff=0.15)
   NEVER put index labels inside the cell rectangle.

5. To highlight a cell, use Indicate(cell) or cell_rect.animate.set_fill(YELLOW, 0.3).
   NEVER reposition the label to highlight — it breaks alignment.

6. For linked-list pointers / arrows between cells, use:
     Arrow(cell_a.get_right(), cell_b.get_left(), buff=0.1)
   or for vertical:
     Arrow(cell_a.get_bottom(), cell_b.get_top(), buff=0.1)

7. Helper pattern for array scenes (copy this approach):
     def make_cell(value, size=1.0):
         rect = Square(side_length=size, color=WHITE)
         label = Text(str(value), font_size=32).move_to(rect.get_center())
         return VGroup(rect, label)
   Then: array_group = VGroup(*[make_cell(v) for v in [3, 7, 1, 9, 2]])
         array_group.arrange(RIGHT, buff=0).move_to(ORIGIN)

=== EXAMPLE: Graph scene with Axes ===
```
from manim import *

class Scene001(Scene):
    def construct(self):
        title = Text("Understanding Derivatives", font_size=42)
        self.play(Write(title), run_time=2)
        self.wait(1)
        self.play(title.animate.to_edge(UP, buff=0.5), run_time=1)

        axes = Axes(
            x_range=[-3, 3, 1], y_range=[-1, 9, 2],
            x_length=8, y_length=4.5,
            axis_config={{"include_numbers": True}},
        ).shift(DOWN * 0.3)
        axes_labels = axes.get_axis_labels(
            x_label=MathTex(r"x"), y_label=MathTex(r"f(x)")
        )
        self.play(Create(axes), Write(axes_labels), run_time=2)
        self.wait(1)

        graph = axes.plot(lambda x: x**2, color=BLUE, x_range=[-2.8, 2.8])
        graph_label = MathTex(r"f(x) = x^2", color=BLUE).scale(0.7)
        graph_label.next_to(axes.c2p(2, 4), RIGHT)
        self.play(Create(graph), run_time=3)
        self.play(Write(graph_label), run_time=1)
        self.wait(2)

        x_val = 1
        slope = 2 * x_val
        tangent = axes.plot(
            lambda x: slope * (x - x_val) + x_val**2,
            color=YELLOW, x_range=[-0.5, 2.5],
        )
        dot = Dot(axes.c2p(x_val, x_val**2), color=YELLOW)
        slope_label = MathTex(r"f'(1) = 2", color=YELLOW).scale(0.7)
        slope_label.next_to(dot, UR, buff=0.3)

        self.play(Create(dot), run_time=1)
        self.play(Create(tangent), Write(slope_label), run_time=2)
        self.wait(3)

        area = axes.get_area(graph, x_range=[0, 2], color=GREEN, opacity=0.3)
        area_label = MathTex(r"\int_0^2 x^2\,dx = \frac{{8}}{{3}}", color=GREEN).scale(0.7)
        area_label.next_to(area, RIGHT, buff=0.3)
        self.play(FadeIn(area), run_time=2)
        self.play(Write(area_label), run_time=1.5)
        self.wait(3)

        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
        self.wait(1)
```

=== EXAMPLE: Equation derivation with MathTex ===
```
from manim import *

class Scene002(Scene):
    def construct(self):
        title = Text("Solving Quadratics", font_size=42)
        self.play(Write(title), run_time=2)
        self.play(title.animate.to_edge(UP, buff=0.5), run_time=1)
        self.wait(1)

        step1 = MathTex(r"x^2 - 5x + 6 = 0", color=BLUE).scale(1.2)
        self.play(Write(step1), run_time=2)
        self.wait(2)

        step2 = MathTex(r"(x - 2)(x - 3) = 0", color=GREEN).scale(1.2)
        step2.move_to(step1)
        self.play(ReplacementTransform(step1, step2), run_time=2)
        self.wait(2)

        step3 = MathTex(r"x = 2 \quad \text{{or}} \quad x = 3", color=YELLOW).scale(1.2)
        step3.move_to(step2)
        self.play(ReplacementTransform(step2, step3), run_time=2)
        box = SurroundingRectangle(step3, color=YELLOW, buff=0.25)
        self.play(Create(box), run_time=1.5)
        self.wait(3)

        self.play(FadeOut(step3), FadeOut(box), run_time=1)

        check_title = Text("Verification:", font_size=32)
        check1 = MathTex(r"(2)^2 - 5(2) + 6 = 0 \checkmark", color=GREEN).scale(0.8)
        check2 = MathTex(r"(3)^2 - 5(3) + 6 = 0 \checkmark", color=GREEN).scale(0.8)
        checks = VGroup(check_title, check1, check2).arrange(DOWN, buff=0.4)
        checks.move_to(ORIGIN)

        self.play(Write(check_title), run_time=1.5)
        self.play(Write(check1), run_time=2)
        self.play(Write(check2), run_time=2)
        self.wait(3)

        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
        self.wait(1)
```

=== EXAMPLE: Array / hash table with properly aligned cells ===
```
from manim import *

class Scene003(Scene):
    def construct(self):
        title = Text("Hash Table with Chaining", font_size=42)
        self.play(Write(title), run_time=2)
        self.play(title.animate.to_edge(UP, buff=0.5), run_time=1)

        def make_cell(value="", size=0.9):
            rect = Square(side_length=size, color=WHITE)
            if value:
                label = Text(str(value), font_size=30).move_to(rect.get_center())
                return VGroup(rect, label)
            return VGroup(rect)

        cells = VGroup(*[make_cell() for _ in range(5)])
        cells.arrange(DOWN, buff=0)
        cells.move_to(LEFT * 2 + DOWN * 0.3)

        indices = VGroup()
        for i, cell in enumerate(cells):
            idx = Text(str(i), font_size=20, color=GRAY)
            idx.next_to(cell, LEFT, buff=0.3)
            indices.add(idx)

        self.play(
            LaggedStart(*[Create(c[0]) for c in cells], lag_ratio=0.15),
            run_time=2,
        )
        self.play(
            LaggedStart(*[Write(idx) for idx in indices], lag_ratio=0.1),
            run_time=1.5,
        )
        self.wait(1)

        val = 7
        slot = val % 5
        op_text = MathTex(r"7 \mod 5 = 2", color=YELLOW).scale(0.9)
        op_text.next_to(cells, RIGHT, buff=1.5)
        self.play(Write(op_text), run_time=2)
        self.wait(1)

        target_cell = cells[slot]
        self.play(target_cell[0].animate.set_fill(YELLOW, 0.3), run_time=1)

        new_label = Text("7", font_size=30, color=GREEN)
        new_label.move_to(target_cell[0].get_center())
        target_cell.add(new_label)
        self.play(Write(new_label), run_time=1.5)
        self.wait(3)

        self.play(*[FadeOut(m) for m in self.mobjects], run_time=1.5)
        self.wait(1)
```

Each scene is ~30 seconds of content. Your scenes should be similar or longer.
"""

    def _build_user_message(self, extracted_text: str, user_prompt: Optional[str]) -> str:
        message = f"""\
Create an educational video with 5-7 scenes based on this source material.
Analyze the material carefully — identify the key concepts, mathematical \
relationships, functions, and problems, then create scenes that VISUALLY \
teach them with rich Manim animations.

--- SOURCE MATERIAL ---
{extracted_text}
--- END SOURCE MATERIAL ---

REQUIREMENTS:
1. Generate 5-7 scenes with complete manim_code for each
2. Total video duration: 1.5 to 3 minutes (sum of all duration_hint_seconds)
3. Each scene must have 30-60 seconds of content
4. Include at least one graph scene with Axes and plotted functions
5. Include at least one equation scene with step-by-step transforms
6. Last scene must be a summary/recap
7. Every scene must have rich, multi-step animations (not just text)
8. Use self.wait() generously between animation groups
"""
        if user_prompt:
            message += f"\nAdditional instructions: {user_prompt}\n"

        message += "\nRespond with ONLY the JSON object. No markdown fences."
        return message

    def _parse_response(self, response_text: str) -> dict:
        text = response_text.strip()
        if text.startswith("```json"):
            text = text[7:]
        if text.startswith("```"):
            text = text[3:]
        if text.endswith("```"):
            text = text[:-3]
        text = text.strip()

        try:
            return json.loads(text)
        except json.JSONDecodeError as e:
            logger.error("[script_gen] Failed to parse JSON: %s", e)
            logger.error("[script_gen] Response text: %s", text[:1000])
            raise ValueError(f"LLM did not return valid JSON: {e}")
